{% set name = "pypmml" %}
{% set version = "0.9.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypmml-{{ version }}.tar.gz
  sha256: 5a5f83e48a0a70494f3badf10d6b2b8124ec77e636b9ec7455842be9a827e604

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - openjdk >=11
  run:
    - python >=3.5
    - openjdk >=11
    - py4j >=0.10.7


test:
  imports:
    - pypmml
    - pypmml.jars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/autodeployai/pypmml
  summary: Python PMML scoring library
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maxibor
